// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nchkfzpjndrcpbwkajxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jaGtmenBqbmRyY3Bid2thanh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjc5ODAsImV4cCI6MjA2MzkwMzk4MH0.zUH3jYtFMpl8BjorDCWAO_itdMWBoXpANMAGtP9qanA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);